### ISSUE TITLE
Math exponents should be allowed in Abstract

### ISSUE THREAD

**Issue by Inventitech** [Inventitech/AbstractFormatter#11]
According to @jon-bell, Math exponents may be allowed in Abstract and could be translated into proper HTML.

**Comment by jon-bell** [comment]
When did I say that? :) Conference publishing sure doesn't like them.

**Comment by Inventitech** [comment]
During ESEC/FSE, you made fun of the AbstractFormatter complaining about your 'complex math'. Proof with your paper: http://jonbell.net/electrictest.pdf

**Comment by jon-bell** [comment]
Ah right. Now I remember :) I agree that they should still be stripped for the plain text abstract, I think that I just thought that it wasn't sufficiently complex to warrant a specific warning ;)

**Comment by Inventitech** [comment]
haha: http://dl.acm.org/citation.cfm?id=2786823
" have taken over 1e300 years. "

**Comment by jon-bell** [comment]
I tried writing out all of the 0’s but it went over the character limit.

**Comment by Inventitech** [comment]
:dancers:

**Comment by Inventitech** [comment]
How do you like this?

**Comment by jon-bell** [comment]
very nice!

**Comment by Inventitech** [comment]
... and we are live! :)
http://abstractformatter.inventitech.com
