### ISSUE TITLE
Latex hyphens not removed

### ISSUE THREAD

**Issue by MichaelHilton** [Inventitech/AbstractFormatter#15]
Sample Abstract:
"Test for abstract formatter from the commu- nity. Develop- ers like it when they have examples of what is wrong."
When pasting this text in, Abstract formatter did not fix the hyphens. 
It should results in:
"Test for abstract formatter from the community. Developers like it when they have examples of what is wrong."

**Comment by Inventitech** [comment]
Oh yeah, this only works for
`Test for abstract formatter from the commu-
nity. Develop-
ers like it when they have examples of what is wrong.`

**Comment by Inventitech** [comment]
Did you paste it in with line breaks? Any specific reasons why there were none in your example? Do you think it should work without them (I don't)?

**Comment by Inventitech** [comment]
@MichaelHilton ?

**Comment by MichaelHilton** [comment]
Sorry for not getting back to you. I was crunched for time in a paper deadline. 
So I did some more investigation this morning, and it turns out that when copy and pasting from Adobe Reader on Mac, You get something like `commu-<EOL> nity`.  However, when copy and pasting from Mac Preview (which I always use when writing in LaTex) you don't get Line Breaks in that situation, instead you only get:  `the commu- nity`.
You get Line Breaks for the paragraphs, but not for the individual lines.  I don't' know if it doesn't have line breaks, or it is doing some "smart" copy and paste that is removing them...

I will close this for now, because it is not AbstractFormatter's fault that Preview is acting up.  

It would be interesting to have a discussion about maybe it is worth collapsing `commu- nity` anyway, I personally can't think of any legal way in English to have a word followed by a hyphen, then a space. 
In fact according to [grammerbook.com](http://www.grammarbook.com/punctuation/hyphens.asp), hyphens should never have spaces around them.  Anyway, just something to think about.

**Comment by Inventitech** [comment]
Yeah, that's what I was suspecting. I have seen similar behavior in some PDFViewers under Linux. I'll make up my mind during and perhaps reopen this issue.
